version: "2.13"

services:

 app:
    container_name: book-api
    image: javabeanstack/book-api:v1
    restart: on-failure
    ports:
     - 3000:3000
    extra_hosts:
      - "host.docker.internal:192.168.50.167"